spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mandatory_model_in_dbms
        username: postgres
        password: pass
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate