spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mandatory_model_in_dbms
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
#    level:
#        org.springframework.web: TRACE